/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//this project to control GPIO Ports A,B with LEDs on PB1,PB13 and push button on PA1 ,PA13 for blue Bill Board
// Verified simulation in proteus


#include <stdint.h>
//
#define RCC_base 0x40021000
#define RCC_CR *((volatile uint32_t * )(RCC_base + 0x00))
#define RCC_CFGR *((volatile uint32_t * )(RCC_base + 0x04))
#define RCC_APB2ENR *((volatile uint32_t * )(RCC_base + 0x18))


#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)

#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)


#define AFIO_base 0x40010000
#define AFIO_EXTICR1 *(volatile uint32_t *)(AFIO_base + 0x08)



void clk_init(void ){

	// enable CLK for port A
	RCC_APB2ENR|=(1<<2) ;

	//enable CLK for Port B
	RCC_APB2ENR|=(1<<3) ;


}
////////////////////////////////////////////////////////////////////////////////
void GPIO_init (void ){

	// configure port A for 2 push button input floating . MODE 0x00 CNF0x01
	// A1
	GPIOA_CRL&=~(0b11<<4) ;
	GPIOA_CRL|=(0x01<<6);
	// A13
	GPIOA_CRH&=~(0b11<<20) ;
	GPIOA_CRH|=(0x01<<22);

	// configure port B for 2 Led output pins Push_Pull. MODE 0x01 CNF0x00
	//B1
	GPIOB_CRL&=~(0b11<<6) ;
	GPIOB_CRL|=(0x01<<4);
	// B13
	GPIOB_CRH&=~(0b11<<22) ;
	GPIOB_CRH|=(0x01<<20);

	GPIOB_ODR |=(1<<13)|(1<<1);
}
//////////////////////////////////////////////////////////////////////////////////
int main(void)
{
	clk_init() ;
	GPIO_init();
	/* Loop forever */

	while (1){
		if(((GPIOA_IDR)&(1<<1))==0)
		{
			GPIOB_ODR^=(0x1<<1);
			while ((GPIOA_IDR&(1<<1))==0);//for single press
		}
		if((GPIOA_IDR&(1<<13))>0)
		{
			GPIOB_ODR^=(0x1<<13);
			//while ((GPIOA_IDR&(1<<1))==0);//for single press
		}
		for (int i = 0 ;i < 2000 ;i++);
	}
	return 0;
}
