/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

#include "STM32F103C6.h"
#include "STM32F103_GPIO.h"
#include "KeyPad.h"
#include "LCD.h"
#include "STM32F103_EXTI.h"
#include "STM32F103_UART.h"
#include "Stm32F103_RCC.h"
#include "STM32F103_SPI.h"
#include "STM32F103_I2C.h"
#include "EEPROM.h"


//#define MCU_MASTER

//#define MCU_SLAVE

void clk_init(void ){

	// enable CLK for port A
	RCC_GPIOA_CLK_EN() ;
	//enable CLK for Port B
	RCC_GPIOB_CLK_EN() ;
	//enable AFIO CLK
	RCC_AFIO_CLK_EN() ;
	//enable I2C CLK
	RCC_I2C1_CLK_EN() ;

}
////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////


//static void _delay_ms(int  loop)
//{
//	for(int j = 0 ; j< loop ; j++)
//		for (int i =0 ;i < 250 ;i++);
//}

int volatile  flag= 0 ;

void EXTI9_CallBack(void)
{
	flag=1 ;
}
int main(void)
{


	clk_init() ;

	EXTI_PinCfg_t  ex1config ;
	ex1config.EXTI_PIN = EXTI9PB9 ;
	ex1config.EXTI_Trigger = EXTI_Trigger_Rising ;
	ex1config.P_IRQ_CallBack = EXTI9_CallBack ;
	ex1config.EXTI_IRQ_EN = EXTI_Enable ;

	MCAL_EXTI_GPIO_Init(&ex1config) ;




	while (1){

		flag = 0 ;

	}
	return 0;
}
