/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

#define RCC_base 0x40021000
#define RCC_CR *((volatile uint32_t * )(RCC_base + 0x00))
#define RCC_CFGR *((volatile uint32_t * )(RCC_base + 0x04))
#define RCC_APB2ENR *((volatile uint32_t * )(RCC_base + 0x18))


#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)


#define EXTI_base 0x40010400
#define EXTI_IMR *(volatile uint32_t *)(EXTI_base + 0x0)
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_base + 0x08)
#define EXTI_PR *(volatile uint32_t *)(EXTI_base + 0x14)

#define NVIC_base 0xE000E100
#define NVIC_ISER0 *(volatile uint32_t *)(NVIC_base + 0x00)

#define AFIO_base 0x40010000
#define AFIO_EXTICR1 *(volatile uint32_t *)(AFIO_base + 0x08)



void clk_init(void ){
	//set PLL * 8
	RCC_CFGR |=(0b0110<<18);
	// select PLL CLK
	RCC_CFGR |=(0b10<<0);
	// PLL ON
	RCC_CR|=(1<<24);
	// set APB2 CLK /4
	RCC_CFGR|=(0b101<<11) ;
	// set APB 1 CLK /2
	RCC_CFGR|=(0b100<<8);
	// set AHB to none pre-scaler
	RCC_CFGR &=~(0b111<<4);


	// enable CLK for port A
	RCC_APB2ENR|=(1<<2) ;
	//enable AFIO
	RCC_APB2ENR|=(1<<0) ;

	while (!((RCC_CR>>25)&1));

}

void EXTI_init(void){
	//enable EXTI0 interrupt
	EXTI_IMR|=(1<<0);
	//CONFIG rising edge
	EXTI_RTSR|=(1<<0);
	//enable nvic
	NVIC_ISER0|=(1<<6);
}

void GPIO_init (void ){
	//Init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000 ;
	//config pin0 in port A
	GPIOA_CRL|=(1<<2);
	//connect PortA.0 to EXTI
	AFIO_EXTICR1 &=~(0b1111<<0);
}

int main(void)
{
	clk_init() ;
	GPIO_init();
	EXTI_init();
	/* Loop forever */

while (1);

return 0;

}

void EXTI0_IRQHandler(void){

	GPIOA_ODR^=(1<<13);

	EXTI_PR|=(1<<0);
}
